import type { CatalogGame } from "./types";

export const SEED_GAMES: CatalogGame[] = [
  { id: "botw", title: "The Legend of Zelda: Breath of the Wild", platforms: ["switch", "wiiu"] },
  { id: "kart", title: "Mario Kart 8 Deluxe", platforms: ["switch"] },
  { id: "totk", title: "Tears of the Kingdom", platforms: ["switch"] },
  { id: "odyssey", title: "Super Mario Odyssey", platforms: ["switch"] },
  { id: "smash", title: "Super Smash Bros. Ultimate", platforms: ["switch"] },
  { id: "animal", title: "Animal Crossing: New Horizons", platforms: ["switch"] },
  { id: "splatoon", title: "Splatoon 3", platforms: ["switch"] },
  { id: "scarlet", title: "Pokémon Scarlet", platforms: ["switch"] },
  { id: "dread", title: "Metroid Dread", platforms: ["switch"] },
  { id: "xenoblade", title: "Xenoblade Chronicles 3", platforms: ["switch"] },
  { id: "elden", title: "Elden Ring", platforms: ["ps5", "xbox-series", "pc"] },
  { id: "astro", title: "Astro Bot", platforms: ["ps5"] },
  { id: "gow", title: "God of War Ragnarök", platforms: ["ps5"] },
  { id: "spider", title: "Marvel's Spider-Man 2", platforms: ["ps5"] },
  { id: "ff16", title: "Final Fantasy XVI", platforms: ["ps5", "pc"] },
  { id: "horizon", title: "Horizon Forbidden West", platforms: ["ps5", "pc"] },
  { id: "returnal", title: "Returnal", platforms: ["ps5", "pc"] },
  { id: "demons", title: "Demon's Souls", platforms: ["ps5"] },
  { id: "hades", title: "Hades", platforms: ["switch", "pc", "ps5"] },
  { id: "bg3", title: "Baldur's Gate 3", platforms: ["pc", "ps5"] },
  { id: "cyber", title: "Cyberpunk 2077", platforms: ["pc", "ps5", "xbox-series"] },
  { id: "disco", title: "Disco Elysium", platforms: ["pc", "switch", "ps5"] },
  { id: "stardew", title: "Stardew Valley", platforms: ["pc", "switch", "ps5"] },
  { id: "witcher", title: "The Witcher 3", platforms: ["pc", "ps5", "switch", "xbox-series"] },
  { id: "celeste", title: "Celeste", platforms: ["pc", "switch", "ps5"] },
  { id: "portal", title: "Portal 2", platforms: ["pc"] },
  { id: "halo", title: "Halo Infinite", platforms: ["xbox-series", "pc"] },
  { id: "silk", title: "Hollow Knight: Silksong", platforms: ["switch", "pc", "ps5"] },
  { id: "ff7", title: "Final Fantasy VII", platforms: ["ps1", "ps4", "switch", "pc"] },
  { id: "p5", title: "Persona 5 Royal", platforms: ["ps4", "ps5", "switch", "pc"] },
];
